In [4]:
from re import A

from pyexpat import features

name = input("What's your name?")
sum = 100+100
print ('hello,%s' %name)
print ('sum = %d' %sum)

hello,cy
sum = 200


In [6]:
sum = 0
number = 1
while number < 100:
    sum = sum + number
    number = number + 2
print (sum)

2500


In [9]:
sum = 0
for number in range(1,100,2):
    sum = sum + number
print (sum)

2500


In [11]:
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.amin(a))
print(np.amin(a,0))
print(np.amin(a,1))
print(np.amax(a))
print(np.amax(a,0))
print(np.amax(a,1))

1
[1 2 3]
[1 4 7]
9
[7 8 9]
[3 6 9]


In [6]:
#numpy作业
import numpy as np
persontype = np.dtype({
    'names':['name', 'chinese', 'english', 'math'],
    'formats':['S32','i', 'i', 'i']})
peoples = np.array([("ZhangFei",66,65,30),("GuanYu",95,85,98),
       ("ZhaoYun",93,92,96),("HuangZhong",90,88,77),("DianWei",80,90,90)], dtype=persontype)
chineses = peoples[:]['chinese']
englishs = peoples[:]['english']
maths = peoples[:]['math']
# 1. 第一个列表：存储「科目名称」和「对应成绩数组」（一一对应）
subjects = [
    ("语文", chineses),
    ("英语", englishs),
    ("数学", maths)
]

# 2. 第二个列表：存储「统计量名称」和「对应numpy计算函数」（一一对应）
statistics = [
    ("均值", np.mean),
    ("最小值", np.min),
    ("最大值", np.max),
    ("方差", np.var),
    ("标准差", np.std)
]
# -------------------------- 两层for循环：遍历所有组合 --------------------------

# 外层循环：遍历每个科目（拿到科目名+该科成绩）
for subj_name, subj_scores in subjects:
    print(f"===== {subj_name} 相关统计 =====")  # 可选：分组打印，更易读
    # 内层循环：遍历每个统计量（拿到统计量名+计算函数）
    for stat_name, stat_func in statistics:
        # 计算结果：用当前统计函数处理当前科目的成绩
        result = stat_func(subj_scores)
        # 打印结果（格式：统计量名 + 数值，保留2位小数更整洁）
        print(f"{stat_name}：{result:.2f}")
    print()  # 可选：科目之间空一行，区分更清晰

total_scores = chineses + englishs + maths
# 获取总成绩降序排序的索引（argsort默认升序，[::-1]反转为降序）
# argsort返回的是「排序后元素在原数组中的索引位置」
sorted_indices = np.argsort(total_scores)[::-1]
# 根据排序索引重排原始数据，得到按总成绩降序的结果
sorted_peoples = peoples[sorted_indices]
# -------------------------- 格式化输出名次 --------------------------
print("=" * 50)
print(f"{'名次':<6}{'姓名':<10}{'语文':<6}{'英语':<6}{'数学':<6}{'总成绩':<6}")
print("-" * 50)

# 遍历排序后的数据，enumerate从1开始计数（表示名次）
for rank, person in enumerate(sorted_peoples, start=1):
    # 注意：name是S32格式（bytes类型），需要解码为字符串
    name = person['name'].decode('utf-8')
    chinese = person['chinese']
    english = person['english']
    math = person['math']
    total = chinese + english + math  # 也可以用 total_scores[sorted_indices[rank-1]]

    # 格式化输出（左对齐，保证排版整齐）
    print(f"{rank:<6}{name:<10}{chinese:<6}{english:<6}{math:<6}{total:<6}")
print("=" * 50)


===== 语文 相关统计 =====
均值：84.80
最小值：66.00
最大值：95.00
方差：114.96
标准差：10.72

===== 英语 相关统计 =====
均值：84.00
最小值：65.00
最大值：92.00
方差：95.60
标准差：9.78

===== 数学 相关统计 =====
均值：78.20
最小值：30.00
最大值：98.00
方差：634.56
标准差：25.19

名次    姓名        语文    英语    数学    总成绩   
--------------------------------------------------
1     ZhaoYun   93    92    96    281   
2     GuanYu    95    85    98    278   
3     DianWei   80    90    90    260   
4     HuangZhong90    88    77    255   
5     ZhangFei  66    65    30    161   


In [2]:
i = 0
while i < 10:
    i += 1
    if i % 2 == 0:
        continue
    print (i)


1
3
5
7
9


In [10]:
heros = ["钢铁侠","绿巨人"]
heros. extend(["鹰眼","灭霸"])
heros[3:]=["李逵","林冲"]
heros[heros. index("绿巨人")] = "神奇女侠"
heros
# s = [1,2,3,4,5]
# s.insert(1,8)
# print(s)

['钢铁侠', '神奇女侠', '鹰眼', '李逵', '林冲']

In [20]:
#二维列表
matrixa = [0]*4
print(matrixa)
for i in range(4):
    matrixa[i] = [0]*4
print(matrixa)


[0, 0, 0, 0]
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [23]:
#浅拷贝
x = [1, 2, 3]
y = x.copy()
z = x[:]
x[1]=1
print (y)
print (z)



[1, 2, 3]
[1, 2, 3]


In [26]:
#深拷贝
import copy
x = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
y = copy.copy(x) #浅拷贝
z = copy.deepcopy(x)
x[1][1]=0
print (x)
print (y)
print (z)

[[1, 2, 3], [4, 0, 6], [7, 8, 9]]
[[1, 2, 3], [4, 0, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [9]:
nums = [3,1,9,6,8,3,5,3]
nums.sort()
nums
nums.reverse()
nums
nums = [3,1,9,6,8,3,5,3]
nums.sort(reverse=True)
nums
nums.count(3)


3

In [7]:
oho = [1,2,3,4,5]
for i in range (len(oho)):
    oho[i] = oho[i]*2
print (oho)
oho = [1,2,3,4,5]
oho = [i*2 for i in oho]
print (oho)
"苟日新，日日新，又日新".split("，")
"".join(["moliseraph","949"])

[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]


'moliseraph949'

In [16]:
year = 1998
"彗尾出生于{}年".format(year)
"{0}{1}{2}{2}".format("臭","色","毛")
"{:.2f}".format(50.0)

'50.00'

In [6]:
x = [1, 2, 3]
y = [4, 5, 6]
zipped = zip(x, y)
list(zipped)
z = [7, 8, 9]
zipped = zip(x, y, z)
list(zipped)
import itertools
z = "huiwei"
zipped = itertools.zip_longest(x, y, z)
list(zipped)

[(1, 4, 'h'),
 (2, 5, 'u'),
 (3, 6, 'i'),
 (None, None, 'w'),
 (None, None, 'e'),
 (None, None, 'i')]

In [12]:
mapped =  map(ord, "fisher")
list(mapped)
mapped= map(pow, [2,3,10],[5,2,3])
list (mapped)
list(filter(str. islower, "Huiwei"))


['u', 'i', 'w', 'e', 'i']

In [15]:
y = {"吕布":"口口布", "关羽":"关习习"}
type(y)
y["刘备"] = "刘baby"
y
b= dict(吕布="口口布", 关羽="关习习", 刘备="刘baby")
b

{'吕布': '口口布', '关羽': '关习习', '刘备': '刘baby'}

In [4]:
def myfunc():
    pass
myfunc()
def myfunc():
    for i in range(3):
        print("maomao")
myfunc()

maomao
maomao
maomao


In [16]:
import pandas as pd
from pandas import DataFrame
from pandasql import sqldf, load_meat, load_births
df1 = DataFrame({'name':['ZhangFei', 'GuanYu','a','b','c'], 'data1': range(5)})
pysqldf = lambda sql: sqldf(sql, globals())
sql = "select * from df1 where name = 'ZhangFei'"
print(pysqldf(sql))

if __name__ == '__main__':
    pysqldf = lambda sql: 1
    print(pysqldf(sql))
    a = "1"

def xiongxiongdawang():
    a = "1"
    print(pysqldf(sql))

xiongxiongdawang()
print(a)

       name  data1
0  ZhangFei      0
1
1
1


In [1]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
#准备数据集
iris = load_iris()
#获取特征集和分类标识
features = iris.data
labels = iris.target
#随机抽取33%的数据作为测试集（预测），其余为训练集
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size=0.33, random_state=0)
#创建CART分类树
clf = DecisionTreeClassifier(criterion='gini')
#拟合构造CART分类树，将训练集的特征值和分类标识作为参数拟合
clf = clf.fit(train_features, train_labels)
#用CART分类树做预测
test_predict = clf.predict(test_features)
#预测结果与测试集结果作比对
score = accuracy_score(test_labels, test_predict)
print("CART分类树准确率 %.4lf" % score)

CART分类树准确率 0.9600
